/*
 * This source file was generated by the Gradle 'init' task
 */
package example.app;

import java.io.IOException;
import java.nio.file.Path;

import dev.vink.k8sclient.config.KubeConfig;
import dev.vink.k8sclient.config.KubeConfigReader;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        KubeConfigReader reader = new KubeConfigReader();
        try {
            KubeConfig config = reader.fromPath(Path.of("C:\\Users\\Public\\Desktop\\.kube\\config"));
            System.out.println(config.getApiVersion());
            System.out.println(config.getClusters().get(0).getCluster().getServer());
        } catch (IOException e) {
            e.printStackTrace();
        }
    }
}
